#!/usr/local/bin/bash

# ---------------------------------------- #
# Programer: PEDRO RIVERO
# Date: Nov 4 2019
# ---------------------------------------- #

BIN_NAME='prr-backup'
DIR_NAME='bin'
INSTALLATION_LOCATION='/usr/local/bin'

BIN_PATH="${INSTALLATION_LOCATION}/${BIN_NAME}"
DIR_PATH="${INSTALLATION_LOCATION}/${BIN_NAME}-${DIR_NAME}"


## ---- UNINSTALL ---- ##

rm -rf ${BIN_PATH} 2>/dev/null
rm -rf ${DIR_PATH} 2>/dev/null

echo "Succesful uninstall of ${BIN_NAME}!"
