#!/usr/local/bin/bash

#    _____  _____
#   |  __ \|  __ \    AUTHOR: Pedro Rivero
#   | |__) | |__) |   ---------------------------------
#   |  ___/|  _  /    DATE: November 12, 2019
#   | |    | | \ \    ---------------------------------
#   |_|    |_|  \_\   https://github.com/pedrorrivero
#

# ---------------------------------------- #
#            NAMING AND SET-UP             #
# ---------------------------------------- #

BIN_NAME='prr-backup'
DIR_NAME='bin'
INSTALLATION_LOCATION='/usr/local/bin'

BIN_PATH="${INSTALLATION_LOCATION}/${BIN_NAME}"
DIR_PATH="${INSTALLATION_LOCATION}/${BIN_NAME}-${DIR_NAME}"


# ---------------------------------------- #
#                UNINSTALL                 #
# ---------------------------------------- #

rm -rf ${BIN_PATH} 2>/dev/null
rm -rf ${DIR_PATH} 2>/dev/null

echo "Succesful uninstall of ${BIN_NAME}!"
